name: WordPress Child Theme Code Quality

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install PHPStan globally
      run: curl -sS https://getcomposer.org/installer | php && php composer.phar global require phpstan/phpstan

    # Run PHPStan (Static Analysis)
    - name: Run PHPStan
      run: ~/.composer/vendor/bin/phpstan analyse --level=2 ./wp-content/themes/my-child-theme

    # Run PHPCS (Code Standards)
    - name: Run PHPCS
      run: vendor/bin/phpcs --standard=WordPress ./wp-content/themes/my-child-theme
